nextorder/urls.py
from django.conf.urls import include, url

from . import views


# Home Page
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

# Branch Urls
urlpatterns += [
    # List
    url(r'^branches/$', views.BranchListView.as_view(), name='branches'),
    # Detail
    url(r'branch/(?P<pk>\d+)$', views.BranchDetailView.as_view(), name='branch-detail'),
]

# Customer Urls
urlpatterns += [
    # List
    url(r'^customers/$', views.CustomerListView.as_view(), name='customers'),
    # Detail
    url(r'customer/(?P<pk>\d+)$', views.CustomerDetailView.as_view(), name='customer-detail'),
]

# Order Urls
urlpatterns += [
    # List
    url(r'^orders/$', views.OrderListView.as_view(), name='orders'),
    # Detail
    url(r'order/(?P<pk>\d+)$', views.OrderDetailView.as_view(), name='order-detail'),
]


# Form Handling
urlpatterns += [   
    url(r'^data/$', views.data_upload, name='data-upload'),
]

recommender/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

#URL pattern mappings
urlpatterns += [
    url(r'^$', RedirectView.as_view(url='/nextorder/', permanent=True)),
    url(r'^nextorder/', include('nextorder.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nextorder/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid # Required for unique book instances
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=50)

class Branch(models.Model):
    branch_name = models.CharField(max_length=50)
    branch_code = models.CharField(max_length=10, blank=True)
    
    def __str__(self):
        return '%s' % (self.branch_name)

class Customer(models.Model):
    phone_number = models.IntegerField(primary_key=True, null=False)
    last_name = models.CharField(max_length = 100, blank=True)
    first_name = models.CharField(max_length = 100, blank=True)
    age = models.IntegerField(null=True)
    email = models.EmailField(blank=True)
    address = models.CharField(max_length = 250, blank=True)

    class Meta:
        ordering = ['first_name']

    def __str__(self):
        return '%s' % (self.first_name)

    def get_abolsute_url(self):
        return reverse('customer-detail', args=[str(self.id)])
        
class Product(models.Model):
    sku = models.CharField(max_length=15, blank=True)
    name = models.CharField(max_length=100, blank=True)
    weight = models.FloatField()
    picture = models.ImageField(upload_to='media/')
    
    def __str__(self):
        return '%s' % (self.name)


class Order(models.Model):
    order_number = models.IntegerField(primary_key=True, null=False) # Primary Key
    customer = models.ForeignKey(Customer, blank=True, null=True)
    order_branch = models.ForeignKey(Branch, blank=True, null=True)
    order_date = models.DateField( blank=True, null=True)
    delivery_date = models.DateField(blank=True, null=True)
#    delivery_date = models.CharField(max_length=15, blank=True)
    payment_total = models.FloatField(null=True)
    payment_advance = models.FloatField(null=True)
    payment_balance = models.FloatField(null=True)

    class Meta:
        ordering = ['-delivery_date']

    def __str__(self):
        return '%s' % (self.order_number)


class Document(models.Model):
    file = models.FileField(upload_to='files/%Y/%m/%d')

nextorder/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.
from .models import Customer, Product, Branch, Order, Document


class DocumentForm(ModelForm):
    class Meta:
        model = Document
        fields = '__all__'

nextorder/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import permission_required

from .models import Customer, Product, Branch, Order, Document
from django.urls import reverse_lazy

from .forms import DocumentForm
from . import client
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.files.storage import FileSystemStorage

import pandas as pd
import csv

# Create your views here.

def index(request):
    """
    View function for home page of site.
    """

    # Generate counts of some of the main objects
    num_branch=Branch.objects.all().count()
    num_customers=Customer.objects.all().count()
    num_products=Product.objects.all().count()
    num_orders=Order.objects.all().count()

    # SESSION TRACKER
    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1


    # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        'index.html',
        context={'num_branch':num_branch,'num_customers':num_customers,'num_products':num_products, 
        'num_orders':num_orders, 'num_visits':num_visits}, # num_visits appended
    )

# Branch
class BranchListView(generic.ListView):
    model = Branch
    paginate_by = 50

class BranchDetailView(generic.DetailView):
    model = Branch

# Customer
class CustomerListView(generic.ListView):
    model = Customer
    paginate_by = 100

class CustomerDetailView(generic.DetailView):
    model = Customer

# Order
class OrderListView(generic.ListView):
    model = Order
    paginate_by = 100

class OrderDetailView(generic.DetailView):
    model = Order


# FORMS HANDLING
def data_upload(request):
 
    # If this is a POST request then process the Form data
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)

        if form.is_valid():
            handle_file(request.FILES['file'])
            return HttpResponseRedirect(reverse('orders'))

    # If this is a GET (or any other method) create the default form.
    else:
        form = DocumentForm()

    return render(request, 'nextorder/file_upload.html', {'form': form})



def handle_file(upfile):
    for chunk in upfile.chunks():
        decoded_file = chunk.decode('utf-8-sig').splitlines() 
        reader = csv.DictReader(decoded_file)

        # for each chunk, read
        for r in reader:
            # if new branch, create branch
            create_branch (r['Branch'])

            # if new customer, create customer else update details
            create_customer (r['Customer Name'], r['Age'], r['Contact #'], r['Email'], r['Address'])

            # Create order 
            create_order (r['Contact #'], r['Branch'], r['Order #'], r['Order Date'], r['Delivery Date'], r['Total Amount'], r['Advance'], r['Balance'])

        # END LOOP
    # END LOOP


def create_branch (str_branch_name):
    try:
        new_branch = Branch.objects.get(branch_name = str_branch_name)
    except Branch.DoesNotExist:
        new_branch = Branch(branch_name = str_branch_name)
        new_branch.save()

# Check if customer already exists. 
# If not, create one. Returns True if created, False if did not create
def create_customer (str_first_name, str_age,str_phone_no,str_email, str_address):

    try:
        int_phone_no = int(str_phone_no)
    except ValueError:
        return False 

    try:
        int_age = int(str_age)
    except ValueError:
        int_age = None 

    try:
        new_customer =  Customer.objects.get(phone_number=int_phone_no)
    except Customer.DoesNotExist:
        new_customer = Customer(
                                phone_number = int_phone_no,
                                first_name = str_first_name,
                                email = str_email,
                                address=str_address,
                                age = int_age
        )
        new_customer.save()

    return True


# Crate Order 
def create_order (str_contact_number, str_order_branch, str_order_number, str_order_date, str_delivery_date, str_payment_total, str_payment_advance, str_payment_balance):

    try:
        int_order_number = int(str_order_number)
        int_contact_number = int(str_contact_number)
    except ValueError as e:
        print ("error converting string inputs to integer. Assigning dummy value")
        return False            

    # Create order Instance
    try:
        new_order = Order.objects.get(order_number=int_order_number) # if found, update details
    except Order.DoesNotExist: # else create a new instance
        new_order = Order() 

    try:
        new_order.order_number = int(str_order_number)
    except ValueError as e:
        print ("error converting "+str_order_number+" to integer. Assigning dummy value")
        return False            
    
    try:
        new_order.payment_total = float(str_payment_total)
    except ValueError as e:
        new_order.payment_total = None

    try:
        new_order.payment_advance = float(str_payment_advance)
    except ValueError as e:
        new_order.payment_advance = None

    try:
        new_order.payment_balance = float(str_payment_balance)
    except ValueError as e:
        new_order.payment_balance = None

    try:
        new_order.order_date = datetime.strptime(str_order_date, '%Y-%m-%d')
    except Exception as e:
        print ("Error creating new order date")

    try: 
        new_order.delivery_date = datetime.strptime(str_delivery_date, '%Y-%m-%d')
    except Exception as e: 
        print ("Error creating order delivery date")

    try:
        new_order.customer = Customer.objects.get(phone_number=int_contact_number) # if found, update details
    except Customer.DoesNotExist:
        new_order.customer = None

    try:
        new_order.order_branch = Branch.objects.get(branch_name=str_order_branch) # if found, update details
    except Branch.DoesNotExist:
        new_order.order_branch = Branch()

    new_order.save()
    return True

nextorder/templates/nextorder/branch_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h3>Title: {{ branch }}</h3>

  <p><strong>Branch:</strong> {{ branch }}</p> <!-- author detail link not yet defined -->
  <p><strong>Orders:</strong> 
    {% for order in branch.order_set.all %} 
        <hr>
            <a href="{% url 'order-detail' order.pk %}">{{ order.order_date }}</a> 

          
    {% endfor %}
    </p>  

{% endblock %}

nextorder/templates/nextorder/branch_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h3>Branch List</h3>

    {% if branch_list %}
    <ul>

      {% for branch in branch_list %}
      <li>
        <a href="{% url 'branch-detail' branch.pk %}">{{ branch }}</a> ({{branch}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no branches!</p>
    {% endif %}       
{% endblock %}

nextorder/templates/nextorder/customer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h3>Title: {{ customer }}</h3>

  <p><strong>Customer:</strong> {{ customer }}</p> 
  <p><strong>Orders:</strong> 
    {% for order in customer.order_set.all %} 
        <hr>
            Number of Orders: {{ customer.order_set.count }} 
        <hr>
            Last order (Order# <a href="{% url 'order-detail' order.pk %}"> {{ order }}</a>) delivered on {{order.delivery_date}} 
            
    {% endfor %}
    </p>  

{% endblock %}

nextorder/templates/nextorder/customer_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h3>Customer List</h3>

    {% if customer_list %}
    <ul>

      {% for customer in customer_list %}
      <hr>
        <a href="{% url 'customer-detail' customer.pk %}">{{ customer }}</a> (Call: {{customer.phone_number}}) 

        <p> Primary Key: {{customer.pk}}</p> 
        <p> Phone Number: {{customer.phone_number}}</p> 
        <p> Last Name: {{customer.last_name}}</p>
        <p> First Name: {{customer.first_name}}</p>
        <p> Age: {{customer.age}}</p>
        <p> Email: {{customer.email}}</p>
        <p> Address: {{customer.address}}</p>

      {% endfor %}

    </ul>
    {% else %}
      <p>There are no customers to display!</p>
    {% endif %}       
{% endblock %}

nextorder/templates/nextorder/file_upload.html
{% extends "base_generic.html" %}
{% block content %}

    <form enctype="multipart/form-data" action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>


    {% if uploaded_file_url %}
        <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}


{% endblock %}

nextorder/templates/nextorder/order_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h3>Title: {{ order }}</h3>

  <p><strong>Order date:</strong> {{ order.order_date }}</p> 
  <p><strong>Delivery date:</strong> {{ order.delivery_date }}</p> 
  <p><strong>Payment Total:</strong> {{ order.payment_total }}</p> 
  <p><strong>Advance:</strong> {{ order.payment_advance }}</p> 
  <p><strong>Balance:</strong> {{ order.payment_balance }}</p> 
  <p><strong>Branch:</strong> <a href="{% url 'branch-detail' order.order_branch.pk %}">{{ order.order_branch.branch_name }}</a></p> 
  <p><strong>customer:</strong> <a href="{% url 'customer-detail' order.customer.pk %}">{{ order.customer.first_name}}</a></p> 

{% endblock %}

nextorder/templates/nextorder/order_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h3>Order List</h3>

    {% if order_list %}
    <ul>

      {% for order in order_list %}
      <li>
          Customer: <a href="{% url 'customer-detail' order.customer.pk %}"> {{order.customer.first_name}} </a> 
          Last Order Delivered on: {{order.delivery_date}} for AED {{order.payment_total}}
          <hr>
          Order# <a href="{% url 'order-detail' order.pk %}"> {{ order }}</a> 
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no orders to display!</p>
    {% endif %}       
{% endblock %}